variables:
  GIT_SSL_NO_VERIFY: "1"
  _R_CHECK_SYSTEM_CLOCK_: 0
  HTTP_PROXY: http://proxy-app.insee.fr:3128
  HTTPS_PROXY: http://proxy-app.insee.fr:3128
  NO_PROXY: insee.test,insee.intra,insee.fr,localhost
  PKG_NAME: "ckm"

image: inseefrlab/onyxia-rstudio:latest

stages:
  - 📘 Documentation

pages:
  stage: 📘 Documentation
  retry:
    max: 2
    when: runner_system_failure
  when: manual
  only:
    - main
    - master
  script:
    - Rscript -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e 'devtools::install(dependencies = FALSE)'
    - Rscript -e "devtools::install_version("pkgdown", version = "2.0.9", dependencies = TRUE)"
    - Rscript -e "options(pkgdown.internet = FALSE) ; pkgdown::build_site()"
  artifacts:
    paths:
      - public

