variables:
  GIT_SSL_NO_VERIFY: "1"
  _R_CHECK_SYSTEM_CLOCK_: 0
  HTTP_PROXY: http://proxy-app.insee.fr:3128
  HTTPS_PROXY: http://proxy-app.insee.fr:3128
  NO_PROXY: insee.test,insee.intra,insee.fr,localhost
  PKG_NAME: "ckm"

image: inseefrlab/onyxia-rstudio:latest

stages:
  - check
  - test
  - deploy

pkg_check:
  stage: check
  tags:
    - docker
  script:
    - R -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - R -e 'devtools::check(check_dir = ".",error_on  = "error",cran = FALSE, document  = FALSE, manual = FALSE)'
  artifacts:
    paths:
      - "${PKG_NAME}_*.tar.gz"

testing:
  stage: test
  tags:
    - docker
  allow_failure: true
  when: on_success
  script:
    - R -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - R -e 'devtools::test()'
  only:
    - main

pages:
  stage: deploy
  dependencies:
    - testing
  tags:
    - docker
  when: on_success
  retry:
    max: 2
    when: runner_system_failure
  script:
    - R -e "install.packages(c('pkgdown','htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - R -e 'devtools::install(dependencies = FALSE)'
    - R -e 'options(pkgdown.internet = FALSE) ; pkgdown::build_site()'
  artifacts:
    paths:
      - public
  only:
    - main
