variables:
  GIT_SSL_NO_VERIFY: "1"
  _R_CHECK_SYSTEM_CLOCK_: 0
  HTTP_PROXY: http://proxy-app.insee.fr:3128
  HTTPS_PROXY: http://proxy-app.insee.fr:3128
  NO_PROXY: insee.test,insee.intra,insee.fr,localhost
  PKG_NAME: "ckm"

image: gitlab-registry.insee.fr:443/datascience/registry-prod/onyxia-rstudio:r4.4.1

stages:
  - check
  - test
  - 📘 Documentation

pkg_check:
  stage: check
  image: inseefrlab/onyxia-rstudio:latest
  script:
    - Rscript -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e 'devtools::check(check_dir = ".",error_on  = "error",cran = FALSE, document  = FALSE, manual = FALSE)'
  artifacts:
    paths:
      - "${PKG_NAME}_*.tar.gz"

testing:
  stage: test
  image: inseefrlab/onyxia-rstudio:latest
  retry:
    max: 2
    when: runner_system_failure
  when: on_success
  script:
    - Rscript -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e 'devtools::test()'
  only:
    - main


pages:
  stage: 📘 Documentation
  retry:
    max: 2
    when: runner_system_failure
  when: manual
  only:
    - main
    - master
  script:
    - Rscript -e 'install.packages("https://packagemanager.posit.co/cran/latest/src/contrib/Archive/pkgdown/pkgdown_2.0.9.tar.gz", repos = NULL, type = "source")'
    - Rscript -e "install.packages(c('htmltools','rmarkdown','dplyr', 'data.table', 'ptable','assertthat','purrr','rlang','utils'), repos='https://nexus.insee.fr/repository/r-cran/', method = 'wget', extra = '--no-check-certificate')"
    - Rscript -e 'devtools::install(dependencies = TRUE)'
    - Rscript -e "options(pkgdown.internet = FALSE) ; pkgdown::build_site()"
  artifacts:
    paths:
      - public

